apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-placementrule
  namespace: operatorhub
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      vendor: OpenShift
