---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: github
  namespace: operatorhub
spec:
  type: GitHub
  pathname: https://github.com/sacharya/acm-labs.git
  configMapRef:
      name: operatorhub-resource-filter-configmap
      kind : configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operatorhub-resource-filter-configmap
  namespace: operatorhub
  labels:
    app: operatorhub
data:
    path: resources/operatorhub/manifest
