apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: operatorhub
  namespace: operatorhub
spec:
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - operatorhub
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
