apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: openshift-disconnected-policy-repomirror
  namespace: default
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.IP Information Protection Processes and Procedures
    policy.mcm.ibm.com/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operator.openshift.io/v1alpha1
        kind: ImageContentSourcePolicy
        metadata:
          name: ubi8repo
        spec:
          repositoryDigestMirrors:
          - mirrors:
            - example.io/example/ubi-minimal
            source: registry.access.redhat.com/ubi8/ubi-minimal
          - mirrors:
            - example.com/example/ubi-minimal
            source: registry.access.redhat.com/ubi8/ubi-minimal
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: openshift-disconnected-binding-repomirror
  namespace: default
placementRef:
  name: openshift-disconnected-placement-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: openshift-disconnected-policy-repomirror
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-disconnected-placement-rule
  namespace: default
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions: [] #- {key: name, operator: In, values: ["spoke"]}

